# Generated by Django 4.2 on 2025-06-01 20:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Kayıt ilk oluşturulduğunda otomatik set edilir', verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Kayıt her güncellendiğinde otomatik güncellenir', verbose_name='Güncellenme Tarihi')),
                ('ad', models.CharField(help_text='Örn: Köpek, Kedi, Golden Retriever', max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Kategori Adı')),
                ('slug', models.SlugField(help_text='SEO dostu URL için otomatik oluşur', max_length=120, unique=True, verbose_name='URL Slug')),
                ('aciklama', models.TextField(blank=True, help_text='Bu kategori hakkında kullanıcılara bilgi veren açıklama', max_length=500, verbose_name='Açıklama')),
                ('pet_type', models.CharField(choices=[('kedi', 'Kedi'), ('kopek', 'Köpek'), ('kus', 'Kuş'), ('balik', 'Balık'), ('kemirgen', 'Kemirgen'), ('surungen', 'Sürüngen'), ('diger', 'Diğer')], default='diger', help_text='Bu kategori hangi hayvan türü için geçerli?', max_length=20, verbose_name='Hayvan Türü')),
                ('ikon_adi', models.CharField(blank=True, help_text='FontAwesome ikon adı (ör: fa-dog, fa-cat)', max_length=50, verbose_name='İkon Adı')),
                ('renk_kodu', models.CharField(default='#6366f1', help_text='Kategori temsil rengi (HEX format)', max_length=7, verbose_name='Renk Kodu')),
                ('kullanim_sayisi', models.PositiveIntegerField(default=0, help_text='Bu kategoride kaç hayvan var', verbose_name='Kullanım Sayısı')),
                ('aktif', models.BooleanField(default=True, help_text='Kategori kullanıcılar tarafından görülebilir mi?', verbose_name='Aktif')),
                ('sira', models.PositiveIntegerField(default=0, help_text='Kategorilerin listeleme sırası', verbose_name='Sıra')),
                ('parent', models.ForeignKey(blank=True, help_text='Bu kategori bir alt kategori ise ana kategorisini seçin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategoriler', to='kategoriler.kategori', verbose_name='Ana Kategori')),
            ],
            options={
                'verbose_name': '🏷️ Kategori',
                'verbose_name_plural': '🏷️ Kategoriler',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='KategoriOzellik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Kayıt ilk oluşturulduğunda otomatik set edilir', verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Kayıt her güncellendiğinde otomatik güncellenir', verbose_name='Güncellenme Tarihi')),
                ('ad', models.CharField(help_text='Örn: Irk, Boy, Kilo, Karakter', max_length=100, verbose_name='Özellik Adı')),
                ('alan_tipi', models.CharField(choices=[('text', 'Metin'), ('number', 'Sayı'), ('select', 'Seçenekli'), ('boolean', 'Evet/Hayır'), ('range', 'Aralık')], default='text', max_length=20, verbose_name='Alan Tipi')),
                ('secenekler', models.JSONField(blank=True, help_text='Seçenekli alan türü için mevcut seçenekler', null=True, verbose_name='Seçenekler')),
                ('zorunlu', models.BooleanField(default=False, help_text='Bu özellik doldurulması zorunlu mu?', verbose_name='Zorunlu')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ozellikler', to='kategoriler.kategori', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': '🔧 Kategori Özelliği',
                'verbose_name_plural': '🔧 Kategori Özellikleri',
                'ordering': ['sira', 'ad'],
                'unique_together': {('kategori', 'ad')},
            },
        ),
        migrations.AddIndex(
            model_name='kategori',
            index=models.Index(fields=['aktif', 'sira'], name='kategoriler_aktif_ba5249_idx'),
        ),
        migrations.AddIndex(
            model_name='kategori',
            index=models.Index(fields=['parent', 'aktif'], name='kategoriler_parent__d90521_idx'),
        ),
        migrations.AddIndex(
            model_name='kategori',
            index=models.Index(fields=['pet_type', 'aktif'], name='kategoriler_pet_typ_6efb27_idx'),
        ),
        migrations.AddIndex(
            model_name='kategori',
            index=models.Index(fields=['slug'], name='kategoriler_slug_1d9d67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kategori',
            unique_together={('ad', 'parent')},
        ),
    ]
