# Generated by Django 4.2.16 on 2025-06-04 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(help_text='Etiket adı benzersiz olmalıdır', max_length=50, unique=True, verbose_name='Etiket Adı')),
                ('slug', models.SlugField(help_text='SEO dostu URL', max_length=60, unique=True, verbose_name='URL Slug')),
                ('aciklama', models.TextField(blank=True, help_text='Etiket hakkında kısa bir açıklama', verbose_name='Açıklama')),
                ('renk_kodu', models.CharField(default='#3B82F6', help_text='Etiketin görsel temsili için HEX renk kodu (örn: #3B82F6)', max_length=7, verbose_name='Renk Kodu')),
                ('ikon', models.CharField(blank=True, help_text='Etiket için isteğe bağlı ikon adı (Font Awesome)', max_length=30, verbose_name='İkon')),
                ('aktif', models.BooleanField(default=True, help_text='Etiketin aktif olup olmadığı', verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': '🏷️ Etiket',
                'verbose_name_plural': '🏷️ Etiketler',
                'ordering': ['ad'],
                'indexes': [models.Index(fields=['slug'], name='etiketler_e_slug_9cdbbf_idx'), models.Index(fields=['aktif'], name='etiketler_e_aktif_7e1e66_idx')],
            },
        ),
    ]
