# Generated by Django 4.2 on 2025-06-01 20:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kategoriler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hayvan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Hayvan Adı')),
                ('slug', models.SlugField(help_text='SEO dostu URL', max_length=150, unique=True, verbose_name='Slug')),
                ('tur', models.CharField(choices=[('kedi', 'Kedi'), ('kopek', 'Köpek'), ('kus', 'Kuş'), ('balik', 'Balık'), ('kemirgen', 'Kemirgen'), ('surungen', 'Sürüngen'), ('diger', 'Diğer')], default='diger', max_length=20, verbose_name='Hayvan Türü')),
                ('yas', models.CharField(blank=True, choices=[('baby', 'Yavru (0-6 ay)'), ('young', 'Genç (6 ay - 2 yaş)'), ('adult', 'Yetişkin (2-7 yaş)'), ('senior', 'Yaşlı (7+ yaş)')], max_length=20, null=True, verbose_name='Yaş')),
                ('cinsiyet', models.CharField(choices=[('male', 'Erkek'), ('female', 'Dişi'), ('unknown', 'Bilinmiyor')], default='unknown', max_length=10, verbose_name='Cinsiyet')),
                ('boyut', models.CharField(blank=True, choices=[('xs', 'Çok Küçük (0-5 kg)'), ('sm', 'Küçük (5-10 kg)'), ('md', 'Orta (10-25 kg)'), ('lg', 'Büyük (25-45 kg)'), ('xl', 'Çok Büyük (45+ kg)')], max_length=5, null=True, verbose_name='Boyut')),
                ('renk', models.CharField(blank=True, max_length=50, verbose_name='Renk')),
                ('kisirlastirilmis', models.BooleanField(default=False, verbose_name='Kısırlaştırılmış')),
                ('asilar_tamam', models.BooleanField(default=False, verbose_name='Aşıları Tam')),
                ('mikrocipli', models.BooleanField(default=False, verbose_name='Mikroçipli')),
                ('karakter_ozellikleri', models.JSONField(blank=True, help_text='Oyuncu, sakin, arkadaş canlısı vb.', null=True, verbose_name='Karakter Özellikleri')),
                ('aciklama', models.TextField(blank=True, help_text='Hayvanın detaylı hikayesi ve özellikleri', verbose_name='Açıklama')),
                ('il', models.CharField(blank=True, choices=[('', '------'), ('istanbul', 'İstanbul'), ('ankara', 'Ankara'), ('izmir', 'İzmir'), ('bursa', 'Bursa'), ('antalya', 'Antalya'), ('konya', 'Konya'), ('adana', 'Adana'), ('gaziantep', 'Gaziantep'), ('mersin', 'Mersin'), ('kayseri', 'Kayseri')], max_length=50, verbose_name='İl')),
                ('ilce', models.CharField(blank=True, max_length=50, verbose_name='İlçe')),
                ('aktif', models.BooleanField(default=True, help_text='Hayvan listede görüntülensin mi?', verbose_name='Aktif')),
                ('sahiplenildi', models.BooleanField(default=False, verbose_name='Sahiplenildi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': '🐾 Hayvan',
                'verbose_name_plural': '🐾 Hayvanlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KopekIrk',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=100, verbose_name='Irk Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('populer', models.BooleanField(default=False, verbose_name='Popüler Irk')),
                ('yerli', models.BooleanField(default=False, verbose_name='Yerli Irk')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': '🐕 Köpek Irkı',
                'verbose_name_plural': '🐕 Köpek Ansiklopedisi',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='HayvanFotograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotograf', models.ImageField(upload_to='hayvanlar/fotograflar/%Y/%m/', verbose_name='Fotoğraf')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='hayvanlar/thumbnails/%Y/%m/', verbose_name='Küçük Resim')),
                ('kapak_fotografi', models.BooleanField(default=False, verbose_name='Kapak Fotoğrafı')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('hayvan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='hayvanlar.hayvan', verbose_name='Hayvan')),
            ],
            options={
                'verbose_name': '🖼️ Hayvan Fotoğrafı',
                'verbose_name_plural': '🖼️ Hayvan Fotoğrafları',
                'ordering': ['sira', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hayvan',
            name='irk',
            field=models.ForeignKey(blank=True, help_text='Köpek ırkı (sadece köpekler için)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hayvanlar.kopekirk', verbose_name='Irk'),
        ),
        migrations.AddField(
            model_name='hayvan',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hayvanlar', to='kategoriler.kategori', verbose_name='Kategori'),
        ),
        migrations.AddIndex(
            model_name='hayvan',
            index=models.Index(fields=['tur'], name='hayvanlar_h_tur_f4be38_idx'),
        ),
        migrations.AddIndex(
            model_name='hayvan',
            index=models.Index(fields=['aktif'], name='hayvanlar_h_aktif_0724cd_idx'),
        ),
        migrations.AddIndex(
            model_name='hayvan',
            index=models.Index(fields=['sahiplenildi'], name='hayvanlar_h_sahiple_4b112d_idx'),
        ),
    ]
