# Generated by Django 4.2 on 2025-06-01 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hayvan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(help_text='Örn: Karabas, Tekir, Pamuk', max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Hayvan Adı')),
                ('slug', models.SlugField(help_text='SEO dostu URL için otomatik oluşur', max_length=120, unique=True, verbose_name='URL Slug')),
                ('aciklama', models.TextField(blank=True, help_text='Bu hayvan hakkında kullanıcılara bilgi veren açıklama', max_length=500, verbose_name='Açıklama')),
                ('pet_type', models.CharField(choices=[('kedi', 'Kedi'), ('kopek', 'Köpek'), ('kus', 'Kuş'), ('balik', 'Balık'), ('kemirgen', 'Kemirgen'), ('surungen', 'Sürüngen'), ('diger', 'Diğer')], default='diger', help_text='Bu hayvan hangi hayvan türüne ait?', max_length=20, verbose_name='Hayvan Türü')),
                ('telefon', models.CharField(blank=True, help_text='İletişim için telefon numarası', max_length=15, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, help_text='İletişim için e-posta adresi', max_length=254, verbose_name='E-posta')),
                ('aktif', models.BooleanField(default=True, help_text='Hayvan ilanı kullanıcılar tarafından görülebilir mi?', verbose_name='Aktif')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Hayvan',
                'verbose_name_plural': 'Hayvanlar',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='KopekIrk',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=100, verbose_name='Irk Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('populer', models.BooleanField(default=False, verbose_name='Popüler Irk')),
                ('yerli', models.BooleanField(default=False, verbose_name='Yerli Irk')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': '🐕 Köpek Irkı',
                'verbose_name_plural': '🐕 Köpek Irkları',
                'ordering': ['ad'],
            },
        ),
    ]
