# Generated by Django 4.2 on 2025-06-01 10:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kategoriler', '0001_initial'),
        ('hayvanlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HayvanFotograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotograf', models.ImageField(upload_to='hayvanlar/fotograflar/%Y/%m/', verbose_name='Fotoğraf')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='hayvanlar/thumbnails/%Y/%m/', verbose_name='Küçük Resim')),
                ('kapak_fotografi', models.BooleanField(default=False, verbose_name='Kapak Fotoğrafı')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('yuklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yüklenme Tarihi')),
            ],
            options={
                'verbose_name': '🖼️ Hayvan Fotoğrafı',
                'verbose_name_plural': '🖼️ Hayvan Fotoğrafları',
                'ordering': ['sira', '-yuklenme_tarihi'],
            },
        ),
        migrations.AlterModelOptions(
            name='hayvan',
            options={'ordering': ['-created_at'], 'verbose_name': '🐾 Hayvan', 'verbose_name_plural': '🐾 Hayvanlar'},
        ),
        migrations.RenameField(
            model_name='hayvan',
            old_name='guncelleme_tarihi',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hayvan',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hayvan',
            name='olusturulma_tarihi',
        ),
        migrations.RemoveField(
            model_name='hayvan',
            name='pet_type',
        ),
        migrations.RemoveField(
            model_name='hayvan',
            name='telefon',
        ),
        migrations.AddField(
            model_name='hayvan',
            name='asilar_tamam',
            field=models.BooleanField(default=False, verbose_name='Aşıları Tam'),
        ),
        migrations.AddField(
            model_name='hayvan',
            name='boyut',
            field=models.CharField(blank=True, choices=[('xs', 'Çok Küçük (0-5 kg)'), ('sm', 'Küçük (5-10 kg)'), ('md', 'Orta (10-25 kg)'), ('lg', 'Büyük (25-45 kg)'), ('xl', 'Çok Büyük (45+ kg)')], max_length=5, null=True, verbose_name='Boyut'),
        ),
        migrations.AddField(
            model_name='hayvan',
            name='cinsiyet',
            field=models.CharField(choices=[('male', 'Erkek'), ('female', 'Dişi'), ('unknown', 'Bilinmiyor')], default='unknown', max_length=10, verbose_name='Cinsiyet'),
        ),
        migrations.AddField(
            model_name='hayvan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='hayvan',
            name='il',
            field=models.CharField(blank=True, max_length=50, verbose_name='İl'),
        ),
        migrations.AddField(
            model_name='hayvan',
            name='ilce',
            field=models.CharField(blank=True, max_length=50, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='hayvan',
            name='irk',
            field=models.ForeignKey(blank=True, help_text='Köpek ırkı (sadece köpekler için)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hayvanlar.kopekirk', verbose_name='Irk'),
        ),
        migrations.AddField(
            model_name='hayvan',
            name='karakter_ozellikleri',
            field=models.JSONField(blank=True, help_text='Oyuncu, sakin, arkadaş canlısı vb.', null=True, verbose_name='Karakter Özellikleri'),
        ),
        migrations.AddField(
            model_name='hayvan',
            name='kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='hayvanlar', to='kategoriler.kategori', verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='hayvan',
            name='kisirlastirilmis',
            field=models.BooleanField(default=False, verbose_name='Kısırlaştırılmış'),
        ),
        migrations.AddField(
            model_name='hayvan',
            name='mikrocipli',
            field=models.BooleanField(default=False, verbose_name='Mikroçipli'),
        ),
        migrations.AddField(
            model_name='hayvan',
            name='renk',
            field=models.CharField(blank=True, max_length=50, verbose_name='Renk'),
        ),
        migrations.AddField(
            model_name='hayvan',
            name='sahiplenildi',
            field=models.BooleanField(default=False, verbose_name='Sahiplenildi'),
        ),
        migrations.AddField(
            model_name='hayvan',
            name='tur',
            field=models.CharField(choices=[('kedi', 'Kedi'), ('kopek', 'Köpek'), ('kus', 'Kuş'), ('balik', 'Balık'), ('kemirgen', 'Kemirgen'), ('surungen', 'Sürüngen'), ('diger', 'Diğer')], default='diger', max_length=20, verbose_name='Hayvan Türü'),
        ),
        migrations.AddField(
            model_name='hayvan',
            name='yas',
            field=models.CharField(blank=True, choices=[('baby', 'Yavru (0-6 ay)'), ('young', 'Genç (6 ay - 2 yaş)'), ('adult', 'Yetişkin (2-7 yaş)'), ('senior', 'Yaşlı (7+ yaş)')], max_length=20, null=True, verbose_name='Yaş'),
        ),
        migrations.AlterField(
            model_name='hayvan',
            name='aciklama',
            field=models.TextField(blank=True, help_text='Hayvanın detaylı hikayesi ve özellikleri', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='hayvan',
            name='ad',
            field=models.CharField(max_length=100, verbose_name='Hayvan Adı'),
        ),
        migrations.AlterField(
            model_name='hayvan',
            name='aktif',
            field=models.BooleanField(default=True, help_text='Hayvan listede görüntülensin mi?', verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='hayvan',
            name='slug',
            field=models.SlugField(help_text='SEO dostu URL', max_length=150, unique=True, verbose_name='Slug'),
        ),
        migrations.AddIndex(
            model_name='hayvan',
            index=models.Index(fields=['tur'], name='hayvanlar_h_tur_f4be38_idx'),
        ),
        migrations.AddIndex(
            model_name='hayvan',
            index=models.Index(fields=['aktif'], name='hayvanlar_h_aktif_0724cd_idx'),
        ),
        migrations.AddIndex(
            model_name='hayvan',
            index=models.Index(fields=['sahiplenildi'], name='hayvanlar_h_sahiple_4b112d_idx'),
        ),
        migrations.AddField(
            model_name='hayvanfotograf',
            name='hayvan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='hayvanlar.hayvan', verbose_name='Hayvan'),
        ),
    ]
