# Generated by Django 4.2 on 2025-06-01 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kategoriler', '0001_initial'),
        ('hayvanlar', '0002_hayvanfotograf_alter_hayvan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hayvanfotograf',
            options={'ordering': ['sira', '-created_at'], 'verbose_name': '🖼️ Hayvan Fotoğrafı', 'verbose_name_plural': '🖼️ Hayvan Fotoğrafları'},
        ),
        migrations.RemoveField(
            model_name='hayvanfotograf',
            name='yuklenme_tarihi',
        ),
        migrations.AddField(
            model_name='hayvanfotograf',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='hayvanfotograf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='hayvan',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hayvanlar', to='kategoriler.kategori', verbose_name='Kategori'),
        ),
    ]
