# Generated by Django 4.2.16 on 2025-06-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hayvanlar', '0003_make_kategori_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kopekirk',
            options={'ordering': ['ad'], 'verbose_name': '🐕 Köpek Irkı', 'verbose_name_plural': '🐕 Köpek Ansiklopedisi'},
        ),
        migrations.AlterField(
            model_name='hayvan',
            name='il',
            field=models.CharField(blank=True, choices=[('', '------'), ('istanbul', 'İstanbul'), ('ankara', 'Ankara'), ('izmir', 'İzmir'), ('bursa', 'Bursa'), ('antalya', 'Antalya'), ('konya', 'Konya'), ('adana', 'Adana'), ('gaziantep', 'Gaziantep'), ('mersin', 'Mersin'), ('kayseri', 'Kayseri')], max_length=50, verbose_name='İl'),
        ),
    ]
