# Generated by Django 4.2.16 on 2025-06-04 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etiketler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hayvanlar', '0004_alter_kopekirk_options_alter_hayvan_il'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaglikDurumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asi_gecmisi', models.JSONField(default=dict, help_text='Her aşı için tarih ve notlar', verbose_name='Aşı Geçmişi')),
                ('kisirlastirma_tarihi', models.DateField(blank=True, null=True, verbose_name='Kısırlaştırma Tarihi')),
                ('son_kontrol', models.DateField(blank=True, null=True, verbose_name='Son Veteriner Kontrolü')),
                ('kronik_hastaliklar', models.TextField(blank=True, verbose_name='Kronik Hastalıklar')),
                ('tedavi_gecmisi', models.TextField(blank=True, verbose_name='Tedavi Geçmişi')),
                ('ozel_bakim', models.TextField(blank=True, verbose_name='Özel Bakım Gereksinimleri')),
                ('notlar', models.TextField(blank=True, verbose_name='Sağlık Notları')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': '🏥 Sağlık Durumu',
                'verbose_name_plural': '🏥 Sağlık Durumları',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='hayvan',
            name='asilar_tamam',
        ),
        migrations.RemoveField(
            model_name='hayvan',
            name='kisirlastirilmis',
        ),
        migrations.RemoveField(
            model_name='hayvan',
            name='mikrocipli',
        ),
        migrations.AddField(
            model_name='hayvan',
            name='etiketler',
            field=models.ManyToManyField(blank=True, related_name='hayvanlar', to='etiketler.etiket', verbose_name='Etiketler'),
        ),
        migrations.AddField(
            model_name='hayvan',
            name='sorumlu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sorumlu_hayvanlar', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu Kişi'),
        ),
        migrations.AlterField(
            model_name='hayvan',
            name='il',
            field=models.CharField(blank=True, max_length=50, verbose_name='İl'),
        ),
        migrations.AddIndex(
            model_name='hayvan',
            index=models.Index(fields=['il', 'kategori'], name='hayvanlar_h_il_24dd62_idx'),
        ),
        migrations.AddIndex(
            model_name='hayvan',
            index=models.Index(fields=['slug'], name='hayvanlar_h_slug_aae7bb_idx'),
        ),
        migrations.AddField(
            model_name='saglikdurumu',
            name='hayvan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saglik', to='hayvanlar.hayvan', verbose_name='Hayvan'),
        ),
    ]
