# Generated by Django 4.2 on 2025-06-01 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hayvanlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Kayıt ilk oluşturulduğunda otomatik set edilir', verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Kayıt her güncellendiğinde otomatik güncellenir', verbose_name='Güncellenme Tarihi')),
                ('baslik', models.CharField(help_text="Örn: 'Sevimli Golden Retriever yuva arıyor'", max_length=200, verbose_name='İlan Başlığı')),
                ('slug', models.SlugField(help_text='SEO dostu URL için otomatik oluşur', max_length=220, unique=True, verbose_name='URL Slug')),
                ('aciklama', models.TextField(help_text='Hayvanın hikayesi, karakteri ve özel ihtiyaçları', verbose_name='İlan Açıklaması')),
                ('ilan_turu', models.CharField(choices=[('sahiplendirme', 'Sahiplendirme'), ('kayip', 'Kayıp Hayvan'), ('bulundu', 'Bulunan Hayvan'), ('baranak', 'Barınak İlanı'), ('gecici_bakici', 'Geçici Bakıcı Aranıyor')], default='sahiplendirme', max_length=20, verbose_name='İlan Türü')),
                ('durum', models.CharField(choices=[('aktif', 'Aktif'), ('beklemede', 'Onay Bekliyor'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi')], default='beklemede', max_length=20, verbose_name='İlan Durumu')),
                ('ilan_veren_adi', models.CharField(max_length=100, verbose_name='İlan Veren Adı')),
                ('ilan_veren_telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('ilan_veren_email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('il', models.CharField(max_length=50, verbose_name='İl')),
                ('ilce', models.CharField(max_length=50, verbose_name='İlçe')),
                ('adres_detay', models.TextField(blank=True, help_text='Mahalle, sokak vb. detay bilgiler', verbose_name='Adres Detayı')),
                ('acil', models.BooleanField(default=False, help_text='Acil durumda olan hayvanlar için', verbose_name='Acil İlan')),
                ('ucretsiz', models.BooleanField(default=True, help_text='Sahiplendirme ücretsiz mi?', verbose_name='Ücretsiz')),
                ('ucret', models.DecimalField(blank=True, decimal_places=2, help_text='Varsa sahiplendirme ücreti', max_digits=10, null=True, verbose_name='Ücret')),
                ('ozel_sartlar', models.TextField(blank=True, help_text='Sahiplendirme için özel şartlar varsa', verbose_name='Özel Şartlar')),
                ('goruntulenme_sayisi', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı')),
                ('favori_sayisi', models.PositiveIntegerField(default=0, verbose_name='Favori Sayısı')),
                ('yayinlanma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Yayınlanma Tarihi')),
                ('son_gecerlilik_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Son Geçerlilik Tarihi')),
                ('moderator_notu', models.TextField(blank=True, verbose_name='Moderatör Notu')),
                ('hayvan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to='hayvanlar.hayvan', verbose_name='Hayvan')),
            ],
            options={
                'verbose_name': '📢 İlan',
                'verbose_name_plural': '📢 İlanlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IlanRapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Kayıt ilk oluşturulduğunda otomatik set edilir', verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Kayıt her güncellendiğinde otomatik güncellenir', verbose_name='Güncellenme Tarihi')),
                ('rapor_eden_email', models.EmailField(max_length=254, verbose_name='Rapor Eden E-posta')),
                ('rapor_nedeni', models.CharField(choices=[('yanlis_bilgi', 'Yanlış Bilgi'), ('spam', 'Spam'), ('uygunsuz_icerik', 'Uygunsuz İçerik'), ('dolandiricilik', 'Dolandırıcılık'), ('diger', 'Diğer')], max_length=50, verbose_name='Rapor Nedeni')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('durum', models.CharField(choices=[('inceleniyor', 'İnceleniyor'), ('cozuldu', 'Çözüldü'), ('gecersiz', 'Geçersiz')], default='inceleniyor', max_length=20, verbose_name='Rapor Durumu')),
                ('moderator_notu', models.TextField(blank=True, verbose_name='Moderatör Notu')),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raporlar', to='ilanlar.ilan', verbose_name='İlan')),
            ],
            options={
                'verbose_name': '🚨 İlan Raporu',
                'verbose_name_plural': '🚨 İlan Raporları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IlanFotograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Kayıt ilk oluşturulduğunda otomatik set edilir', verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Kayıt her güncellendiğinde otomatik güncellenir', verbose_name='Güncellenme Tarihi')),
                ('fotograf', models.ImageField(upload_to='ilanlar/fotograflar/%Y/%m/', verbose_name='Fotoğraf')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='ilanlar/thumbnails/%Y/%m/', verbose_name='Küçük Resim')),
                ('kapak_fotografi', models.BooleanField(default=False, verbose_name='Kapak Fotoğrafı')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='Fotoğraf Açıklaması')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='ilanlar.ilan', verbose_name='İlan')),
            ],
            options={
                'verbose_name': '📸 İlan Fotoğrafı',
                'verbose_name_plural': '📸 İlan Fotoğrafları',
                'ordering': ['sira', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IlanBasvuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Kayıt ilk oluşturulduğunda otomatik set edilir', verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Kayıt her güncellendiğinde otomatik güncellenir', verbose_name='Güncellenme Tarihi')),
                ('basvuran_adi', models.CharField(max_length=100, verbose_name='Başvuran Adı')),
                ('basvuran_telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('basvuran_email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('mesaj', models.TextField(help_text='Neden bu hayvanı sahiplenmek istiyorsunuz?', verbose_name='Mesaj')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='beklemede', max_length=20, verbose_name='Başvuru Durumu')),
                ('ilan_veren_notu', models.TextField(blank=True, verbose_name='İlan Veren Notu')),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basvurular', to='ilanlar.ilan', verbose_name='İlan')),
            ],
            options={
                'verbose_name': '📝 İlan Başvurusu',
                'verbose_name_plural': '📝 İlan Başvuruları',
                'ordering': ['-created_at'],
                'unique_together': {('ilan', 'basvuran_email')},
            },
        ),
        migrations.AddIndex(
            model_name='ilan',
            index=models.Index(fields=['durum', 'ilan_turu'], name='ilanlar_ila_durum_75f052_idx'),
        ),
        migrations.AddIndex(
            model_name='ilan',
            index=models.Index(fields=['il', 'ilce'], name='ilanlar_ila_il_730621_idx'),
        ),
        migrations.AddIndex(
            model_name='ilan',
            index=models.Index(fields=['acil', 'durum'], name='ilanlar_ila_acil_473b39_idx'),
        ),
        migrations.AddIndex(
            model_name='ilan',
            index=models.Index(fields=['yayinlanma_tarihi'], name='ilanlar_ila_yayinla_a59f60_idx'),
        ),
    ]
